import React, { useState } from "react";
import questions from "./data/questions";
import QuestionCard from "./components/QuestionCard";
import ResultChart from "./components/ResultChart";

const App = () => {
  const [answers, setAnswers] = useState(Array(questions.length).fill(null));
  const [showResults, setShowResults] = useState(false);

  const handleAnswer = (index, value) => {
    const newAnswers = [...answers];
    newAnswers[index] = value;
    setAnswers(newAnswers);
  };

  const calculateEmissions = () => {
    const emissions = {
      CO: 0,
      NOx: 0,
      SO2: 0,
      PM25: 0,
      VOC: 0,
    };

    answers.forEach((ans, index) => {
      const impact = questions[index].impact[ans] || {};
      Object.entries(impact).forEach(([key, val]) => {
        emissions[key] += val;
      });
    });

    return emissions;

    
  };

  return (
    <div className="container">
      <h1 style={{ textAlign: "center", fontSize: "2rem", marginBottom: "1rem" }}>
        Criteria Footprint Tracker
      </h1>
      <p id="p">A footprint tracker for your annual Criteria pollutant emissions</p>
      {!showResults ? (
        <>
          {questions.map((q, i) => (
            <QuestionCard
              key={i}
              question={q.question}
              options={q.options}
              selected={answers[i]}
              onSelect={(val) => handleAnswer(i, val)}
            />
          ))}
          <button
            className="button"
            onClick={() => setShowResults(true)}
          >
            Submit
          </button>
        </>
      ) : (
        <ResultChart data={calculateEmissions()} />
      )}

      <footer>
        <p id="copy">&copy; Siddhesh Umesh Sarang</p>
      </footer>

      <p id="discl">This report is generated by <span><a href="https://criteriareports.vercel.app">criteriareports.vercel.app</a></span></p>
    </div>
  );
};

export default App;
